# Generated by Django 3.1.3 on 2021-01-01 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7, verbose_name='Fiyat'),
            preserve_default=False,
        ),
    ]
