# Generated by Django 3.1.7 on 2021-03-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210106_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='complete',
            field=models.CharField(choices=[('Gümrük İşlemleri', 'Gümrük İşlemleri'), ('Yolda', 'Yolda'), ('Teslim Edildi', 'Teslim Edildi')], default=False, max_length=20, verbose_name='Sipariş Durumu'),
        ),
    ]
