# Generated by Django 3.1.7 on 2021-03-18 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210318_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Müşteri Adı')),
                ('address', models.CharField(max_length=200, verbose_name='Adres')),
                ('city', models.CharField(max_length=200, verbose_name='Şehir')),
                ('state', models.CharField(max_length=200, verbose_name='Ülke')),
                ('zipcode', models.CharField(max_length=200, verbose_name='Posta Kodu')),
                ('phone', models.CharField(max_length=200, verbose_name='Telefon Numarası')),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Oluşturulma Tarihi')),
                ('email', models.CharField(default='test@mail.com', max_length=200, verbose_name='Mail')),
            ],
        ),
    ]
