# Generated by Django 3.1.3 on 2020-12-31 14:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=100, null=True, verbose_name='Takip Numarası')),
                ('agency_number', models.CharField(max_length=100, null=True, verbose_name='Acenta Numarası')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ağırlık')),
                ('to_country', models.CharField(max_length=100, null=True, verbose_name='Varış Ülkesi')),
                ('shipping_status', models.CharField(choices=[('Gümrük İşlemleri', 'Gümrük İşlemleri'), ('Yolda', 'Yolda'), ('Teslim Edildi', 'Teslim Edildi')], default=True, max_length=50, verbose_name='Sipariş Durumu:')),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Oluşturulma Tarihi')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer', verbose_name='Müşteri')),
            ],
        ),
    ]
