# Generated by Django 3.1.3 on 2020-12-31 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dollar', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Kur Fiyatı')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Alış Fiyatı')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ağırlık')),
                ('y_cargo', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Yurtiçi Kargo')),
                ('logistics', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Lojistik')),
                ('customs', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Gümrük Vergisi')),
                ('tax', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='KDV')),
                ('coupon', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Kuponlar')),
                ('ae_commission', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Paltform Komisyon')),
                ('affiliate', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Affiliate')),
                ('sum_comissions', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Toplam Kesinti')),
                ('ae_remaining', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='AE - Kalan')),
                ('net_profit', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Net Kar ($)')),
                ('net_profit_tl', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Net Kar (TL)')),
                ('profit_margin', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Kar Marjı')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Ürün')),
            ],
        ),
    ]
