# Generated by Django 3.1.3 on 2021-01-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='sum_comissions',
        ),
        migrations.AddField(
            model_name='commission',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7, verbose_name='Satış Fiyatı'),
            preserve_default=False,
        ),
    ]
