# Generated by Django 3.1.3 on 2021-01-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0005_auto_20210105_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='ae_commission_rate',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Platform Komisyon Oranı'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='affiliate',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Affiliate'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='coupon',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Kuponlar'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='customs',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Gümrük Vergisi'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='logistics',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Lojistik'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Alış Fiyatı'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Satış Fiyatı'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='tax',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='KDV'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='y_cargo',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Yurtiçi Kargo'),
        ),
    ]
