# Generated by Django 3.1.3 on 2021-01-06 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0006_auto_20210105_0202'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commission',
        ),
    ]
