# Generated by Django 3.1.3 on 2021-01-07 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0004_auto_20210107_0050'),
        ('commissions', '0008_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracks.track', verbose_name='Tedarik'),
        ),
    ]
