# Generated by Django 3.1.3 on 2021-01-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0010_commission_ae_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='dollar',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7, verbose_name='Kur Fiyatı'),
            preserve_default=False,
        ),
    ]
