# Generated by Django 3.1.3 on 2021-01-10 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0012_auto_20210108_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commission',
            old_name='product',
            new_name='track_product',
        ),
    ]
