# Generated by Django 3.1.3 on 2021-01-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sku', models.CharField(max_length=200, verbose_name='Ürün ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ürün Adı')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Orjinal Fiyat')),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='İndirimli Fiyat')),
                ('quantity', models.CharField(max_length=200, verbose_name='Stok Adet')),
                ('link', models.CharField(max_length=200, null=True, verbose_name='Ürün Linki')),
                ('marketplace', models.CharField(max_length=200, null=True, verbose_name='Pazaryeri')),
            ],
        ),
    ]
