# Generated by Django 3.1.3 on 2021-01-03 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_suply'),
    ]

    operations = [
        migrations.AddField(
            model_name='suply',
            name='aeproduct_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='AE- Ürün ID'),
        ),
    ]
