# Generated by Django 3.1.3 on 2021-01-04 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_suply_aeproduct_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suply',
        ),
    ]
