# Generated by Django 3.1.3 on 2021-01-08 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_logistics_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='logistics',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Ürün Adı'),
        ),
        migrations.AddField(
            model_name='tax',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Ürün Adı'),
        ),
    ]
