# Generated by Django 3.1.3 on 2020-12-31 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='Ürün Adı')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Fiyat')),
                ('discount_price', models.IntegerField(blank=True, null=True, verbose_name='İndirim Fiyatı')),
                ('link', models.CharField(max_length=200, null=True, verbose_name='Link ')),
                ('rating', models.CharField(max_length=200, null=True, verbose_name='Ürün Yorumları')),
                ('decription', models.CharField(max_length=5000, null=True, verbose_name='Ürün Açıklaması')),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Oluşturulma Tarihi')),
            ],
        ),
    ]
