# Generated by Django 3.1.3 on 2021-01-06 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='decription',
        ),
        migrations.RemoveField(
            model_name='track',
            name='rating',
        ),
    ]
