# Generated by Django 3.1.3 on 2021-01-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_auto_20210107_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='sku',
            field=models.CharField(max_length=200, null=True, verbose_name='Ürün SKU'),
        ),
    ]
