# Generated by Django 3.1.3 on 2021-01-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_track_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=7, verbose_name='İndirim Fiyatı'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='track',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Fiyat'),
        ),
    ]
