# Generated by Django 3.1.7 on 2021-03-17 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Cari Adı')),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Oluşturulma Tarihi')),
            ],
        ),
    ]
