# Generated by Django 3.1.3 on 2020-12-31 14:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Müşteri Adı')),
                ('address', models.CharField(max_length=200, verbose_name='Adres')),
                ('city', models.CharField(max_length=200, verbose_name='Şehir')),
                ('state', models.CharField(max_length=200, verbose_name='Ülke')),
                ('zipcode', models.CharField(max_length=200, verbose_name='Posta Kodu')),
                ('phone', models.CharField(max_length=200, verbose_name='Telefon Numarası')),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Oluşturulma Tarihi')),
                ('email', models.CharField(default='test@mail.com', max_length=200, verbose_name='Mail')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Admin')),
            ],
        ),
    ]
