# Generated by Django 3.1.3 on 2021-01-01 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Tedarikçi Adı'),
        ),
    ]
