# Generated by Django 3.1.6 on 2021-03-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=220, verbose_name='Ürün Adı')),
                ('url', models.URLField(verbose_name='Ürün Linki')),
                ('current_price', models.FloatField(blank=True, verbose_name='Yeni Fiyat')),
                ('old_price', models.FloatField(default=0, verbose_name='Eski Fiyat')),
                ('price_difference', models.FloatField(default=0, verbose_name='Fiyat Farkı')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Günceleme Tarihi')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
            ],
        ),
    ]
