# Generated by Django 3.1.7 on 2021-03-17 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketplaces',
            options={'ordering': ('price_difference', '-created')},
        ),
    ]
