# Generated by Django 3.1.3 on 2020-12-29 12:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Müşteri Adı')),
                ('address', models.CharField(max_length=200, verbose_name='Adres')),
                ('city', models.CharField(max_length=200, verbose_name='Şehir')),
                ('state', models.CharField(max_length=200, verbose_name='Ülke')),
                ('zipcode', models.CharField(max_length=200, verbose_name='Posta Kodu')),
                ('phone', models.CharField(max_length=200, verbose_name='Telefon Numarası')),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Oluşturulma Tarihi')),
                ('email', models.CharField(default='test@mail.com', max_length=200, verbose_name='Mail')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Admin')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ürün Adı')),
                ('product_id', models.CharField(max_length=200, verbose_name='Ürün ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Fiyat')),
                ('quantity', models.CharField(max_length=200, verbose_name='Stok Adet')),
                ('image', models.ImageField(blank=True, default='img/default.png', null=True, upload_to='img', verbose_name='Ürün Resim')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='Ürün Adı')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Fiyat')),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='İndirim Fiyatı')),
                ('brand', models.CharField(max_length=200, null=True, verbose_name='Marka')),
                ('link', models.CharField(max_length=200, null=True, verbose_name='Link ')),
                ('images', models.CharField(max_length=1000, null=True, verbose_name='Resim Link')),
                ('decription', models.CharField(max_length=1000, null=True, verbose_name='Ürün Yorumları')),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trancking_number', models.CharField(max_length=100, null=True, verbose_name='Takip Numarası')),
                ('agency_number', models.CharField(max_length=100, null=True, verbose_name='Acenta Numarası')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ağırlık')),
                ('to_country', models.CharField(max_length=100, null=True, verbose_name='Varış Ülkesi')),
                ('shipping_status', models.CharField(choices=[('Gümrük İşlemleri', 'Gümrük İşlemleri'), ('Yolda', 'Yolda'), ('Teslim Edildi', 'Teslim Edildi')], default=True, max_length=50, verbose_name='Sipariş Durumu:')),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Oluşturulma Tarihi')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.customer', verbose_name='Müşteri')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=100, null=True, verbose_name='Sipariş Numarası')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Adet')),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Oluşturulma Tarihi')),
                ('complete', models.BooleanField(default=False, verbose_name='Sipariş Durumu')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.customer', verbose_name='Müşteri Bilgisi')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.product', verbose_name='Ürün Bilgisi')),
            ],
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Alış Fiyatı')),
                ('m_price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Maliyet $')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ağırlık')),
                ('y_cargo', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Yurtiçi Kargo')),
                ('logistics', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Lojistik')),
                ('customs', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Gümrük Vergisi')),
                ('tax', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='KDV')),
                ('p_cost', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Ürün Maliyeti')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Satış Fiyatı')),
                ('coupon', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Satış Fiyatı')),
                ('ae_commission', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Paltform Komisyon')),
                ('affiliate', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Affiliate')),
                ('sum_comissions', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Toplam Kesinti')),
                ('ae_remaining', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='AE - Kalan')),
                ('net_profit', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Net Kar ($)')),
                ('net_profit_tl', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Net Kar (TL)')),
                ('profit_margin', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Kar Marjı')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.product', verbose_name='Ürün')),
            ],
        ),
    ]
