# Generated by Django 3.1.3 on 2020-12-29 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20201229_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='decription',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='track',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='track',
            name='images',
        ),
    ]
