# Generated by Django 3.1.3 on 2020-12-29 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20201230_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='m_price',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='p_cost',
        ),
        migrations.AddField(
            model_name='commission',
            name='dollar',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7, verbose_name='Kur Fiyatı'),
            preserve_default=False,
        ),
    ]
