# Generated by Django 3.1.3 on 2020-12-30 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20201230_0228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='sale_price',
        ),
    ]
